apiVersion: v1
kind: Service
metadata:
  name: keyword-extraction-service
spec:
  nodeSelector:
    kubernetes.io/arch: arm64
  selector:
    app: keyword-extraction
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
